// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package bot

import (
	"github.com/acomagu/musicbot/soundplayer"
	"sync"
)

var (
	lockVoiceChannelJoinerMockJoinVoiceChannel sync.RWMutex
)

// VoiceChannelJoinerMock is a mock implementation of VoiceChannelJoiner.
//
//     func TestSomethingThatUsesVoiceChannelJoiner(t *testing.T) {
//
//         // make and configure a mocked VoiceChannelJoiner
//         mockedVoiceChannelJoiner := &VoiceChannelJoinerMock{
//             JoinVoiceChannelFunc: func(in1 string, in2 string) (soundplayer.VC, error) {
// 	               panic("mock out the JoinVoiceChannel method")
//             },
//         }
//
//         // use mockedVoiceChannelJoiner in code that requires VoiceChannelJoiner
//         // and then make assertions.
//
//     }
type VoiceChannelJoinerMock struct {
	// JoinVoiceChannelFunc mocks the JoinVoiceChannel method.
	JoinVoiceChannelFunc func(in1 string, in2 string) (soundplayer.VC, error)

	// calls tracks calls to the methods.
	calls struct {
		// JoinVoiceChannel holds details about calls to the JoinVoiceChannel method.
		JoinVoiceChannel []struct {
			// In1 is the in1 argument value.
			In1 string
			// In2 is the in2 argument value.
			In2 string
		}
	}
}

// JoinVoiceChannel calls JoinVoiceChannelFunc.
func (mock *VoiceChannelJoinerMock) JoinVoiceChannel(in1 string, in2 string) (soundplayer.VC, error) {
	if mock.JoinVoiceChannelFunc == nil {
		panic("VoiceChannelJoinerMock.JoinVoiceChannelFunc: method is nil but VoiceChannelJoiner.JoinVoiceChannel was just called")
	}
	callInfo := struct {
		In1 string
		In2 string
	}{
		In1: in1,
		In2: in2,
	}
	lockVoiceChannelJoinerMockJoinVoiceChannel.Lock()
	mock.calls.JoinVoiceChannel = append(mock.calls.JoinVoiceChannel, callInfo)
	lockVoiceChannelJoinerMockJoinVoiceChannel.Unlock()
	return mock.JoinVoiceChannelFunc(in1, in2)
}

// JoinVoiceChannelCalls gets all the calls that were made to JoinVoiceChannel.
// Check the length with:
//     len(mockedVoiceChannelJoiner.JoinVoiceChannelCalls())
func (mock *VoiceChannelJoinerMock) JoinVoiceChannelCalls() []struct {
	In1 string
	In2 string
} {
	var calls []struct {
		In1 string
		In2 string
	}
	lockVoiceChannelJoinerMockJoinVoiceChannel.RLock()
	calls = mock.calls.JoinVoiceChannel
	lockVoiceChannelJoinerMockJoinVoiceChannel.RUnlock()
	return calls
}
